@startuml

' === Enumeraciones ===
enum Estado {
DISPONIBLE
VENDIDO
}

enum TipoCombustible {
GASOLINA
DIESEL
HIBRIDO
ELECTRICO
}

enum Traccion {
DELANTERA
TRASERA 4X4
}

enum NivelConfort{
BASICO
MEDIO
PREMIUM
}

enum TipoTransmision{
MANUAL
AUTOMATICA
}

' ===Interfaz===
interface Valorable {
+double calcularDepreciacion()
}
@enduml