@startuml

' === Enumeraciones ===
enum Estado {
DISPONIBLE
VENDIDO
}

enum TipoCombustible {
GASOLINA
DIESEL
HIBRIDO
ELECTRICO
}

enum Traccion {
DELANTERA
TRASERA 4X4
}

enum NivelConfort{
BASICO
MEDIO
PREMIUM
}

enum TipoTransmision{
MANUAL
AUTOMATICA
}

' ===Interfaz===
interface Valorable {
+double calcularDepreciacion()
}

' === Clase Persona ===
class Persona {
  -String nombre
  -String apellidos
  -String dni
  -int anioNacimiento
  -LocalDate fechaCaducidadCarnet

  +boolean validarDNI()
  +int calcularAniosCarnet()
}

' === Clase abstracta Vehiculo ===
abstract class Vehiculo {
  -String matricula
  -String marca
  -String modelo
  -int anioFabricacion
  -int kilometraje
  -double precio
  -Estado estado
  -Persona propietario

  +String imprimirDatos()
  +String calcularRiesgo()
}

' === Clase Coche ===
class Coche {
  -int numPuertas
  -TipoCombustible tipoCombustible
  -int capacidadMaletero
  -Traccion traccion
}

' === Subtipos de Coche ===
class Sedan {
  -double espacioInterior
  -NivelConfort nivelConfort
}

class SUV {
  -boolean capacidadOffroad
  -double alturaLibreSuelo
}

class Deportivo {
  -double aceleracion0a100
  -int potenciaCV
  -boolean tieneModoPista
}

' === Clase Moto y subtipos ===
class Moto {
  -int cilindrada
  -int peso
  -double alturaAsiento
  -TipoTransmision tipoTransmision
}

class Scooter {
  -int espacioBajoAsiento
}

class MotoDeportiva {
  -double velocidadMaxima
  -boolean tieneQuickShifter
}

Vehiculo <|-- Moto
Moto <|-- Scooter
Moto <|-- MotoDeportiva

Coche <|-- Sedan
Coche <|-- SUV
Coche <|-- Deportivo

Vehiculo <|-- Coche

Vehiculo ..|> Valorable

Vehiculo o-- Persona : propietario



@enduml